name: Snyk

on: [pull_request]

jobs:
  Security-SCA:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies with pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --deploy --dev
      - name: SCA - Snyk
        uses: snyk/actions/python-3.8@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_API_KEY }}