name: SCA [Snyk]

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies with pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --deploy --dev
      - name: Install Snyk
        run: npm install -g snyk
      - name: Configure Snyk Auth
        with:
          SNYK_API_KEY: ${{ secrets.SNYK_API_KEY }}
        run: snyk config set api=$SNYK_API_KEY
      - name: SCA - Snyk
        run: |
          snyk test